---
- hosts: all
  connection: local
  tasks:
        - name: Deleating S3 bucket
          aws_s3: 
                aws_access_key: 
                aws_secret_key: 
                bucket: 
                mode: delete                
